### ISSUE TITLE
`400` HTTP error

### ISSUE THREAD

**Issue by ehmicky** [AshikNesin/netlify-build-plugin-pushover#2]
Some build is experiencing a `400` when calling `POST https://api.pushover.net/1/messages.json` on the `onError` event handler.

The request payload was:

```json
{
  "user": "{edited}",
  "token":"{edited}@{edited}.net",
  "title": "Netlify Build",
  "message": "Hi there, Latest build failed 😱\\\\n\\\\nCheck your build's log for more details\\\\n\\\\n👉 https://www.byronwade.com",
  "priority": 1,
  "sound": "alien"
}
```

Do you know what the error might be?

**Comment by AshikNesin** [comment]
@ehmicky 

Based on the [docs](https://pushover.net/api#friendly), Pushover responds with 4xx if the **token/user is invalid or their app is over the quota**

![image](https://user-images.githubusercontent.com/4201088/83268918-f0556d80-a1e3-11ea-918f-f5596c201513.png)

And as for the payload I just checked it with my credentials and it works as expected. So it's not an issue with the payload message.

![image](https://user-images.githubusercontent.com/4201088/83268328-19c1c980-a1e3-11ea-8be7-e84ab6f5f78f.png)

Probably if we look into the response that is send by them (400) we might get more context on that issue.

**Comment by ehmicky** [comment]
Thanks for the explanation!

I don't think the HTTP response is available in the `error` object (at least I did not see any). If there was a way to capture the HTTP response and add it to the `error.message` or to any `error` static property, this would show up to users, which help them diagnose what went wrong.

Another thing is: uncaught exceptions in plugins are reported as plugin bugs. To report errors as user errors instead, the [`utils.build.failBuild()`](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#error-reporting) can be used such as:

```js
try {
  doSomething()
  // Errors there are most likely user errors
} catch (error) {
  utils.build.failBuild('doSomething failed!', { error })
}
```

**Comment by AshikNesin** [comment]
@ehmicky Thanks for the suggestions.  I've implemented the  utils.build.failBuild() and well as displaying the error message in the logs

![image](https://user-images.githubusercontent.com/4201088/83278880-e5093e80-a1f1-11ea-854f-fdbf83f4cc65.png)

Will submit PR with latest version :)

**Comment by AshikNesin** [comment]
This issue is addressed in the commit https://github.com/AshikNesin/netlify-plugin-pushover/commit/894b4b33fb551d84e791734b547e1c2df3715d7e

Hence closing it :)
