### ISSUE TITLE
Differentiate Production, Branch and Deploy Previews

### ISSUE THREAD

**Issue by Jacob-JA-Shanks** [AshikNesin/netlify-build-plugin-pushover#4]
Not sure if Netlify allows compatibility to do this, but it would be good if the plugin could deliver different notifications if the build is a branch or preview. That way the notification is more accurate.

**Comment by AshikNesin** [comment]
@Jacob-JA-Shanks Yeah, that option would be great. I'll check the feasibility and implement it.

**Comment by bharathvaj-ganesan** [comment]
@Jacob-JA-Shanks @AshikNesin #8 will solve this issue, where the consumer can set different notification messages based on the site deploy context.
